/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.frame;

import br.com.satc.objetos.Aluno;
import br.com.satc.objetos.Nota;
import br.com.satc.objetos.TipoAvaliacao;
import com.sun.org.apache.xml.internal.serialize.Method;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {

    Aluno a;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTituloALuno = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jTFMatricula = new javax.swing.JTextField();
        jTFNomeAluno = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLTituloNota = new javax.swing.JLabel();
        jLNota4 = new javax.swing.JLabel();
        jLNota1 = new javax.swing.JLabel();
        jLNota2 = new javax.swing.JLabel();
        jLNota3 = new javax.swing.JLabel();
        jLNomeDisciplina = new javax.swing.JLabel();
        jTFNomeDisciplina = new javax.swing.JTextField();
        jBCalcularNota = new javax.swing.JButton();
        jTFNota3 = new javax.swing.JTextField();
        jTFNota4 = new javax.swing.JTextField();
        jTFNota1 = new javax.swing.JTextField();
        jTFNota2 = new javax.swing.JTextField();
        jCBTipoAvaliacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLTituloALuno.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLTituloALuno.setText("Aluno");

        jLMatricula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLMatricula.setText("Matrícula");

        jLNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLNome.setText("Nome");

        jTFMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMatriculaActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLTituloALuno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLMatricula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFNomeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jBCadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFMatricula)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloALuno)
                .addGap(35, 35, 35)
                .addComponent(jLMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBCadastrar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Consulta  de disciplina");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLTituloNota.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLTituloNota.setText("Notas");

        jLNota4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLNota4.setText("N4");

        jLNota1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLNota1.setText("N1");

        jLNota2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLNota2.setText("N2");

        jLNota3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLNota3.setText("N3");

        jLNomeDisciplina.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLNomeDisciplina.setText("Nome da Disciplina");

        jTFNomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeDisciplinaActionPerformed(evt);
            }
        });

        jBCalcularNota.setText("Calcular");
        jBCalcularNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularNotaActionPerformed(evt);
            }
        });

        jCBTipoAvaliacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione a opção>", "Avaliação individual", "Trabalho", "Seminário" }));
        jCBTipoAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLNomeDisciplina))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFNomeDisciplina))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBTipoAvaliacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNota1)
                            .addComponent(jLNota3)
                            .addComponent(jLNota4)
                            .addComponent(jLNota2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTituloNota)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBCalcularNota)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloNota)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNota1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNota2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNota3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFNota3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNota4)
                    .addComponent(jTFNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jBCalcularNota)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLNomeDisciplina)
                .addGap(18, 18, 18)
                .addComponent(jTFNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCBTipoAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMatriculaActionPerformed

    private void jBCalcularNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularNotaActionPerformed

        Aluno a = new Aluno(jTFNomeAluno.getText(), Integer.parseInt(jTFMatricula.getText()));

        String nomeDisciplina = this.jTFNomeDisciplina.getText();
        float nota1, nota2, nota3, nota4, media;
        nota1 = Float.parseFloat(this.jTFNota1.getText());
        nota2 = Float.parseFloat(this.jTFNota2.getText());
        nota3 = Float.parseFloat(this.jTFNota3.getText());
        nota4 = Float.parseFloat(this.jTFNota4.getText());
        media = (nota1 + nota2 + nota3 + nota4) / 4;

        TipoAvaliacao tipo = null;

        switch (jCBTipoAvaliacao.getSelectedIndex()) {
            case 0:

                tipo = TipoAvaliacao.PROVA;

                break;

            case 1:

                tipo = TipoAvaliacao.TRABALHO;
                break;

            case 2:

                tipo = TipoAvaliacao.SEMINARIO;
                break;

        }
        JOptionPane.showMessageDialog(this, "\n" + a + "\n Disciplina: " + nomeDisciplina + "\n Média: " + media + "\n" + tipo.getNomeAvaliacao());

        a.getNotas().add(new Nota(jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFNota1.getText())));
        a.getNotas().add(new Nota(jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFNota2.getText())));
        a.getNotas().add(new Nota(jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFNota3.getText())));
        a.getNotas().add(new Nota(jTFNomeDisciplina.getText(), tipo, Float.parseFloat(jTFNota4.getText())));
        

    }//GEN-LAST:event_jBCalcularNotaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed

        String nome = jTFNomeAluno.getText();
        int matricula = 0;
        try {
            matricula = Integer.parseInt(this.jTFMatricula.getText());

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(this, "Você digitou um caractere invalido");
            throw new RuntimeException();
        }
        a = new Aluno(nome, matricula);
        JOptionPane.showMessageDialog(this, a.toString());


    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jTFNomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeDisciplinaActionPerformed

    private void jCBTipoAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoAvaliacaoActionPerformed


    }//GEN-LAST:event_jCBTipoAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCalcularNota;
    private javax.swing.JComboBox<String> jCBTipoAvaliacao;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNomeDisciplina;
    private javax.swing.JLabel jLNota1;
    private javax.swing.JLabel jLNota2;
    private javax.swing.JLabel jLNota3;
    private javax.swing.JLabel jLNota4;
    private javax.swing.JLabel jLTituloALuno;
    private javax.swing.JLabel jLTituloNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFNomeAluno;
    private javax.swing.JTextField jTFNomeDisciplina;
    private javax.swing.JTextField jTFNota1;
    private javax.swing.JTextField jTFNota2;
    private javax.swing.JTextField jTFNota3;
    private javax.swing.JTextField jTFNota4;
    // End of variables declaration//GEN-END:variables
}
